version: '3.7'

services:
  backend:
    container_name: api-service
    restart: unless-stopped
    build: ../expsvc
    ports:
      - '3001:3001'
    #env_file: ./nodejs/.env
    environment:
      - NODE_ENV=dev
    networks:
      - internal
    # depends_on:
    #   - db

  frontend:
    container_name: api-client
    restart: unless-stopped
    build: ./
    environment:
      - NODE_PATH=/app-client/src
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - internal

  # db:
  #   container_name: mongodb
  #   image: mongo
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_DATABASE: node-app
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo_data:/data/db
  #     - mongo_config:/data/configdb
  #   networks:
  #     - internal

networks:
  internal:

# volumes:
#   mongo_data: {}
#   mongo_config: {}